import { 
  LayoutDashboard, 
  BrainCircuit, 
  BookOpen, 
  FolderHeart, 
  GraduationCap, 
  BarChart3, 
  Settings, 
  Plus,
  Search,
  Sparkles,
  Bell,
  ArrowRight,
  Timer,
  Volume2,
  ChevronRight,
  History,
  Zap,
  Eye,
  Ear,
  Type,
  Layers,
  Accessibility,
  Check,
  X,
  Bold,
  List,
  Paperclip,
  ShoppingBag,
  IceCream,
  Pencil,
  TrendingUp,
  VolumeX,
  CloudRain,
  Wind,
  Coffee,
  Trees,
  Trash2
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Focus: BrainCircuit,
  Reading: BookOpen,
  Organization: FolderHeart,
  Module: GraduationCap,
  Progress: BarChart3,
  Settings: Settings,
  Add: Plus,
  Search: Search,
  AI: Sparkles,
  Notifications: Bell,
  ArrowRight: ArrowRight,
  Timer: Timer,
  Volume: Volume2,
  ChevronRight: ChevronRight,
  Repeat: History,
  Enable: Zap,
  Visual: Eye,
  Auditory: Ear,
  ReadingStyle: Type,
  MixedStyle: Layers,
  Accessibility: Accessibility,
  Check: Check,
  Close: X,
  Bold: Bold,
  List: List,
  Attachment: Paperclip,
  ShoppingBag: ShoppingBag,
  IceCream: IceCream,
  Pencil: Pencil,
  TrendingUp: TrendingUp,
  VolumeX: VolumeX,
  Rain: CloudRain,
  Wind: Wind,
  Cafe: Coffee,
  Forest: Trees,
  Trash: Trash2,
  BarChart3: BarChart3,
  History: History,
  FolderHeart: FolderHeart
};
